url: "https://jesse-visser.nl"
baseurl: ""
title: "Jesse Visser"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .idea/
  - assets/css/.sass-cache/
  - node_modules
sass:
  sass_dir: node_modules
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
ignore_theme_config: true
collections:
  projects:
    output: true
  wip:
    output: true
  cartridges:
    output: true