url: "https://jesse-visser.nl"
baseurl: ""
title: "Jesse Visser"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .idea/
  - assets/bootstrap/js/
  - assets/bootstrap/scss/
  - assets/css/.sass-cache/
sass:
  sass_dir: _bootstrap
  style: compressed
ignore_theme_config: true
collections:
  projects:
    output: true