url: ""
baseurl: ""
title: "Jesse Visser"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .idea/
  - assets/bootstrap/js/
  - assets/bootstrap/scss/
  - assets/css/.sass-cache/
ignore_theme_config: true
collections:
  projects:
    output: true